export const eventData = {
     "silo": {
        id: "silo",
        archive: true,
        link: "https://www.youtube.com/playlist?list=PLrX2ek2EKWv9LVokyX4fczENwx9GTBbtq",
        yt_links: [
            "https://www.youtube.com/embed/videoseries?si=eQ8giE-pehdG_Za4&amp;controls=0&amp;list=PLrX2ek2EKWv9LVokyX4fczENwx9GTBbtq",
            "https://www.youtube.com/embed/TS_EMkqpoG4?si=nFgwcx_zJcxj9wLq",
            "https://www.youtube.com/embed/7gRlb8VPNlo",
            "https://www.youtube.com/embed/5VV3t8zWCC4?si=vZXoWfGLEMnIi5LU",
            "https://www.youtube.com/embed/j1bedAyQaJM?si=dmdhmCYXzc-3OKzg",
        ],
        title: "Level III at SILO",
        location: "SILO - Brooklyn, NY",
        date: "20th July 2024",
        flyerSrc: "flyers/silo.jpeg",
    },
     "elsewhere+05042024": {
        id: "elsewhere+05042024",
        archive: true,
        link: "https://link.dice.fm/Mc9925e3a7d8?dice_id=Mc9925e3a7d8&sharer_id=5e39c6e6d30dd07ee1114829&sharer=fan",
        title: "Level III at Elsewhere - Zone 1",
        location: "Elsewhere - Brooklyn, NY",
        date: "4th May 2024",
        flyerSrc: "flyers/elsewheremay4.jpeg",
        caption: "Join us for this event...",
        images: [
            "elsewhere050424/1.jpg",
            "elsewhere050424/2.jpg",
            "elsewhere050424/3.jpg",
            "elsewhere050424/4.jpg",
            "elsewhere050424/5.jpg",
            "elsewhere050424/6.jpg",
            "elsewhere050424/7.jpg", 
            "elsewhere050424/8.jpg", 
            "elsewhere050424/9.jpg", 
            "elsewhere050424/10.jpg",
            "elsewhere050424/11.jpg", 
            "elsewhere050424/12.jpg", 
            "elsewhere050424/13.jpg", 
        ]
    },
    "bossa+civic": {
        id: "bossa+civic",
        archive: true,
        link: "https://ra.co/events/1887803",
        title: "Level III x Halfmoon BK",
        location: "Bossa Nova Civic Club - Brooklyn NY",
        date: "31st March 2024",
        flyerSrc: "flyers/bossanova.jpeg",
        caption: "Join us for this event...",
        images: [
             "bossaxhalfmoon/Bossahalfmoon1.jpg",
             "bossaxhalfmoon/Bossahalfmoon2.jpg",
             "bossaxhalfmoon/Bossahalfmoon3.jpg",
             "bossaxhalfmoon/Bossahalfmoon4.jpg",
             "bossaxhalfmoon/Bossahalfmoon5.jpg",
             "bossaxhalfmoon/Bossahalfmoon6.jpg",
             "bossaxhalfmoon/Bossahalfmoon7.jpg",
             "bossaxhalfmoon/Bossahalfmoon8.jpg",
             "bossaxhalfmoon/Bossahalfmoon9.jpg",
             "bossaxhalfmoon/Bossahalfmoon10.jpg",
             "bossaxhalfmoon/Bossahalfmoon11.jpg",
             "bossaxhalfmoon/Bossahalfmoon12.jpg",
             "bossaxhalfmoon/Bossahalfmoon13.jpg",
             "bossaxhalfmoon/Bossahalfmoon14.jpg",
             "bossaxhalfmoon/Bossahalfmoon15.jpg",
             "bossaxhalfmoon/Bossahalfmoon16.jpg",
             "bossaxhalfmoon/Bossahalfmoon17.jpg",
             "bossaxhalfmoon/Bossahalfmoon18.jpg",
             "bossaxhalfmoon/Bossahalfmoon19.jpg",    
        ]
    },
    "ludlow": {
        id: "ludlow",
        archive: true,
        title: "Level III Sound Session",
        location: "Ludlow House - New York, NY",
        date: "5th January 2024",
        flyerSrc: "flyers/ludlow_house.jpeg",
        caption: "Join us for this event...",
        images: [
            "ludlow/1.jpg",
            "ludlow/2.jpg",
            "ludlow/3.jpg",
            "ludlow/4.jpg",
            "ludlow/5.jpg",
            "ludlow/6.jpg",
            "ludlow/7.jpg", 
            "ludlow/8.jpg", 
            "ludlow/9.jpg", 
            "ludlow/10.jpg",
            "ludlow/11.jpg", 
            "ludlow/12.jpg", 
            "ludlow/13.jpg", 
        ]
   },          
    "open+the+garage": {
        archive: true,
        title: "Level III Presents: Open the Garage!",
        location: "Lume Studios - Chelsea, NY",
        date: "4th March 2023",
        id: "open+the+garage",
        flyerSrc: "flyers/lume_green.jpeg",
        caption: "Join us for this event...",
        images: [
            "garage/1.jpg",
            "garage/2.jpg",
            "garage/3.jpg",
            "garage/4.jpg",
            "garage/5.jpg",
            "garage/6.jpg",
            "garage/7.jpg", 
            "garage/8.jpg", 
            "garage/9.jpg", 
            "garage/10.jpg", 
        ]
    },
    "its+too+loud": {
        id: "its+too+loud",
        archive: true,
        title: "Level III Presents: It's Too Loud!",
        location: "Bogart House - Brooklyn, NY",
        date: "28th January 2023",
        flyerSrc: "flyers/its_too_loud.jpeg",
        caption: "Join us for this event...",
        images: [
            "loud/1.jpg",
            "loud/2.jpg",
            "loud/3.jpg",
            "loud/4.jpg",
            "loud/5.jpg",
            "loud/6.jpg",
            "loud/7.jpg", 
            "loud/8.jpg", 
            "loud/9.jpg", 
            "loud/10.jpg",
            "loud/11.jpg", 
            "loud/12.jpg",
            "loud/13.jpg",
            // More images
        ]
    },
    "convocation": {
        id: "convocation",
        archive: true,
        title: "Level III Presents: CONVOCATION",
        location: "Kind Regards - New York, NY",
        date: "16th June 2023",
        flyerSrc: "flyers/kind_regards.jpeg",
        caption: "Join us for this event...",
        images: [
            "convocation/1.jpg",
            "convocation/2.jpg",
            "convocation/3.jpg",
            "convocation/4.jpg",
            "convocation/5.jpg",
            "convocation/6.jpg",
            "convocation/7.jpg",
        ]
    }
};
