export const eventData = {
    "ludlow": {
        id: "ludlow",
        archive: true,
        title: "Sound Session",
        location: "Ludlow House",
        date: "5th January 2024",
        flyerSrc: "flyers/ludlow_house.jpeg",
        caption: "Join us for this event...",
        images: [
            "ludlow/1.jpg",
            "ludlow/2.jpg",
            "ludlow/3.jpg",
            "ludlow/4.jpg",
            "ludlow/5.jpg",
            "ludlow/6.jpg",
            "ludlow/7.jpg", 
            "ludlow/8.jpg", 
            "ludlow/9.jpg", 
            "ludlow/10.jpg",
            "ludlow/11.jpg", 
            "ludlow/12.jpg", 
            "ludlow/13.jpg", 
            // More images
        ]
    },
    "its+too+loud": {
        archive: true,
        title: "It's Too Loud!",
        location: "Bogart House",
        date: "28th January 2023",
        id: "its+too+loud",
        flyerSrc: "flyers/its_too_loud.jpeg",
        caption: "Join us for this event...",
        images: [
            "too_loud/1.jpg",
            "too_loud/2.jpg",
            "too_loud/3.jpg",
            "too_loud/4.jpg",
            "too_loud/5.jpg",
            "too_loud/6.jpg",
            "too_loud/7.jpg", 
            "too_loud/8.jpg", 
            "too_loud/9.jpg", 
            "too_loud/10.jpg",
            "too_loud/11.jpg", 
            "too_loud/12.jpg",
            // More images
        ]
    },
    "open+the+garage": {
        archive: true,
        title: "Open the Garage!",
        location: "Lume Studios",
        date: "4th March 2023",
        id: "open+the+garage",
        flyerSrc: "flyers/lume_green.jpeg",
        caption: "Join us for this event...",
        images: [
            "open_garage/1.jpg",
            "open_garage/2.jpg",
            "open_garage/3.jpg",
            "open_garage/4.jpg",
            "open_garage/5.jpg",
            "open_garage/6.jpg",
            "open_garage/7.jpg", 
            "open_garage/8.jpg", 
            "open_garage/9.jpg", 
            "open_garage/10.jpg", 
        ]
    },
    "convocation": {
        archive: true,
        title: "CONVOCATION",
        location: "Kind Regards",
        date: "16th June 2023",
        id: "convocation",
        flyerSrc: "flyers/kind_regards.jpeg",
        caption: "Join us for this event...",
        images: [
            "convocation/1.jpg",
            "convocation/2.jpg",
            "convocation/3.jpg",
            "convocation/4.jpg",
            "convocation/5.jpg",
            "convocation/6.jpg",
            "convocation/7.jpg",
        ]
    }
};